### ISSUE TITLE
Tasks Todo

### ISSUE THREAD

**Issue by AniCricKet** [AniCricKet/ZDL-PACTAPP#1]
- [x] Add "Del Norte High School" above the logo
- [x] Switch the order of car type and miles per month questions and indicate that miles per month is for car
- [x] Ask the user how much (%) they want to decrease their footprint by and link that to a blog on ways to decrease footprint
- [x] Change the data values of the graph so its not scaled by 10^-7
- [x] Make app more visually appealing by adding more tabs which have things like eshaan's animations
- [x] Add help functions for miles per month question, air travel miles, and home energy questions
- [ ] Add countdown clock: https://www.globalwarmingindex.org/
